name: Deploy to DreamHost

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Latest version of checkout action

      # Check if there are changes in .css, .js, .jsx files
      - name: Check for frontend changes
        id: frontend_changes
        run: |
          git diff --name-only HEAD^ HEAD | grep -E '\.(css|js|jsx)$' || echo "no" > no-changes.txt

      # Conditionally run npm build if changes are found in .css, .js, .jsx files
      - name: Set up Node.js
        if: steps.frontend_changes.outputs.frontend_changed != 'no'
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*" # Automatically picks the latest LTS version

      - name: Install dependencies and build frontend
        if: steps.frontend_changes.outputs.frontend_changed != 'no'
        run: |
          npm install
          npm run build

      # SSH to DreamHost and deploy the changes
      - name: Deploy to DreamHost
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/medieor/medieor.earth
            git pull origin main
            php artisan optimize

      # Conditionally sync the build folder if there were frontend changes
      - name: Rsync Build Folder
        if: steps.frontend_changes.outputs.frontend_changed != 'no'
        run: |
          rsync -avz --delete public/build/ ${{ secrets.USER }}@${{ secrets.HOST }}:/home/medieor/medieor.earth/public/build
        env:
          RSYNC_PASSWORD: ${{ secrets.PASSWORD }}
