name: Test Deploy to DreamHost

# This allows you to trigger the workflow manually
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Add server to known_hosts to avoid host key verification failure
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh  # Create .ssh directory if it doesn't exist
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      # Deploy to DreamHost to test SSH and rsync functionality
      - name: Deploy to DreamHost
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            echo "Test SSH connection successful!"  # Test SSH connection

      # Use rsync to sync a test folder
      - name: Sync test folder using rsync with password
        run: |
          mkdir -p public/test-build  # Create a dummy folder
          echo "This is a test file." > public/test-build/test.txt  # Create dummy file
          rsync -avz --delete public/test-build/ ${{ secrets.USER }}@${{ secrets.HOST }}:/home/medieor/medieor.earth/public/test-build
        env:
          RSYNC_PASSWORD: ${{ secrets.PASSWORD }}
