name: Test Deploy to DreamHost

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Add server to known_hosts to avoid host key verification failure
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh  # Create .ssh directory if it doesn't exist
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      # Install sshpass to enable password-based rsync authentication
      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      # Test SSH connection and deploy to DreamHost
      - name: Test SSH connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            echo "SSH connection successful!"

      # Use sshpass with rsync for password-based SSH authentication
      - name: Sync test folder using rsync with password
        run: |
          mkdir -p public/test-build  # Create a dummy folder
          echo "This is a test file." > public/test-build/test.txt  # Create dummy file
          sshpass -p "${{ secrets.PASSWORD }}" rsync -avz --delete public/test-build/ ${{ secrets.USER }}@${{ secrets.HOST }}:/home/medieor/medieor.earth/public/test-build
